services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    environment:
      - PORT=${PORT:-3000}
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
    command: >
      /bin/sh -c "envsubst '$$PORT $$ACTIVE_POOL' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && 
      nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "8081:${PORT}"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "8082:${PORT}"
